### ISSUE TITLE
Mapping from object with nullable to non nullable throws exception

### ISSUE THREAD

**Issue by brendan-rice** [dclucas/MOO#12]
I have a ViewModel that has a nullable int (int? Year), and I am trying to map it to a Model with the same property as an int (int Year).

Moo throws an exception in this instance. Is there any way to tell moo to map the nullable to the int?

**Comment by dclucas** [comment]
Mapping from a nullable to a non-nullable type may lead you to inconsistent behavior, so Moo does not try to deal with it automatically.

In such cases, you can add a custom rule. In part of your web initialization code, you can do something such as:

``` C#
 MappingRepository.Default
   .AddMapping<MyViewModel, MyModel>()
   .From(s => s.MyNullableInteger.Value)
   .To(t => t.MyNonNullableInteger);
```

Please notice that the code above would throw an exception in case your ViewModel has a null value for MyNullableInteger.

**Comment by dclucas** [comment]
Assuming the answer resolved the issue. Please let me know if I should reopen it.
